// src/App.tsx
import React, { useState } from 'react';
import { QueryClient, QueryClientProvider } from 'react-query';
import { AzureConfig } from './types/azure';
import ConfigForm from './components/ConfigForm';
import Explorer from './components/Explorer';

const queryClient = new QueryClient();

function App() {
  const [config, setConfig] = useState<AzureConfig | null>(null);

  return (
    <QueryClientProvider client={queryClient}>
      <div className="min-h-screen bg-gray-100 p-4">
        <div className="max-w-6xl mx-auto">
          {!config ? (
            <div className="max-w-md mx-auto mt-20">
              <ConfigForm onSubmit={setConfig} />
            </div>
          ) : (
            <Explorer config={config} />
          )}
        </div>
      </div>
    </QueryClientProvider>
  );
}

export default App;

// src/App.vue
<template>
  <div class="min-h-screen bg-gray-100 p-4">
    <div class="max-w-6xl mx-auto">
      <div v-if="!config" class="max-w-md mx-auto mt-20">
        <ConfigForm @submit="setConfig" />
      </div>
      <Explorer v-else :config="config" />
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import ConfigForm from './components/ConfigForm.vue';
import Explorer from './components/Explorer.vue';
import type { AzureConfig } from './types/azure';

const config = ref<AzureConfig | null>(null);

const setConfig = (newConfig: AzureConfig) => {
  config.value = newConfig;
};
</script>
